package main

import (
	"bytes"
	"encoding/json"
)

func EmitGoogle(compiled Compiled) string {
	var buf bytes.Buffer

	for _, row := range compiled.GoogleRows {
		buf.WriteString(row.Input)
		buf.WriteByte('\t')
		buf.WriteString(row.Output)
		buf.WriteByte('\t')
		buf.WriteString(row.Next)
		buf.WriteByte('\n')
	}

	return buf.String()
}

func EmitYAML(compiled Compiled) string {
	var buf bytes.Buffer

	buf.WriteString("# Generated by googleime-romatable-generator\n")
	buf.WriteString("# You can add YAML comments to maintain custom notes.\n")
	buf.WriteString("single_rules:\n")
	for _, rule := range compiled.SingleRules {
		buf.WriteString("  - input: ")
		buf.WriteString(yamlString(rule.Input))
		buf.WriteByte('\n')
		buf.WriteString("    output: ")
		buf.WriteString(yamlString(rule.Output))
		buf.WriteByte('\n')
	}

	buf.WriteString("layer_keys:\n")
	for _, rule := range compiled.LayerKeys {
		buf.WriteString("  - input: ")
		buf.WriteString(yamlString(rule.Input))
		buf.WriteByte('\n')
		buf.WriteString("    next: ")
		buf.WriteString(yamlString(rule.Next))
		buf.WriteByte('\n')
	}

	buf.WriteString("sequence_rules:\n")
	for _, rule := range compiled.SequenceRules {
		buf.WriteString("  - input: ")
		buf.WriteString(yamlString(rule.Input))
		buf.WriteByte('\n')
		buf.WriteString("    output: ")
		buf.WriteString(yamlString(rule.Output))
		buf.WriteByte('\n')
	}

	return buf.String()
}

func yamlString(value string) string {
	encoded, _ := json.Marshal(value)
	return string(encoded)
}
